/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Tania
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBienvenida = new javax.swing.JLabel();
        bCrearUsuario = new javax.swing.JButton();
        bEditarUsuario = new javax.swing.JButton();
        bCrearPelicula = new javax.swing.JButton();
        bBuscarPelicula = new javax.swing.JButton();
        bEliminarPelicula = new javax.swing.JButton();
        bCrearSerie = new javax.swing.JButton();
        campoUsername = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        labUsername = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        labNombrePelicula = new javax.swing.JLabel();
        campoNombrePelicula = new javax.swing.JTextField();
        labResumen = new javax.swing.JLabel();
        campoResumen = new javax.swing.JTextField();
        labYear = new javax.swing.JLabel();
        labDirector = new javax.swing.JLabel();
        campoAnos = new javax.swing.JTextField();
        campoDirector = new javax.swing.JTextField();
        labNombreSeries = new javax.swing.JLabel();
        labTemporadas = new javax.swing.JLabel();
        labEpisodios = new javax.swing.JLabel();
        campoNombreSeries = new javax.swing.JTextField();
        campoTemporadas = new javax.swing.JTextField();
        camposEpisodios = new javax.swing.JTextField();
        bBuscarSerie = new javax.swing.JButton();
        bEliminarSerie = new javax.swing.JButton();
        labApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBienvenida.setText("BIENVENIDO A REDFLIXPRO");

        bCrearUsuario.setText("CREAR USUARIO");
        bCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearUsuarioActionPerformed(evt);
            }
        });

        bEditarUsuario.setText("EDITAR USUARIO");

        bCrearPelicula.setText("CREAR PELICULA");
        bCrearPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearPeliculaActionPerformed(evt);
            }
        });

        bBuscarPelicula.setText("BUSCAR PELICULA");
        bBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarPeliculaActionPerformed(evt);
            }
        });

        bEliminarPelicula.setText("ELIMINAR PELICULA");
        bEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarPeliculaActionPerformed(evt);
            }
        });

        bCrearSerie.setText("CREAR SERIE");

        campoUsername.setColumns(10);
        campoUsername.setText("username");

        campoNombre.setColumns(10);
        campoNombre.setText("Nombre");
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        labUsername.setText("USERNAME");

        labNombre.setText("NOMBRE");

        labNombrePelicula.setText("NOMBRE");

        campoNombrePelicula.setColumns(10);
        campoNombrePelicula.setText("Nombre pelicula");

        labResumen.setText("RESUMEN");

        campoResumen.setColumns(10);
        campoResumen.setText("Resumen");

        labYear.setText("AÑO");

        labDirector.setText("DIRECTOR");

        campoAnos.setColumns(10);
        campoAnos.setText("Año");

        campoDirector.setColumns(10);
        campoDirector.setText("Director");

        labNombreSeries.setText("NOMBRE");

        labTemporadas.setText("# TEMPORADAS");

        labEpisodios.setText("# EPISODIOS");

        campoNombreSeries.setColumns(10);
        campoNombreSeries.setText("Nombre series");

        campoTemporadas.setColumns(10);
        campoTemporadas.setText("Temporadas");

        camposEpisodios.setColumns(10);
        camposEpisodios.setText("Episodios");

        bBuscarSerie.setText("BUSCAR SERIE");
        bBuscarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarSerieActionPerformed(evt);
            }
        });

        bEliminarSerie.setText("ELIMINAR SERIE");
        bEliminarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarSerieActionPerformed(evt);
            }
        });

        labApellido.setText("APELLIDO");

        campoApellido.setColumns(10);
        campoApellido.setText("Apellido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labYear)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labDirector)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoDirector))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labNombrePelicula)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoNombrePelicula))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labResumen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bEliminarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bBuscarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bCrearPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labUsername)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labNombre)
                                        .addComponent(labApellido))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoNombre)
                                        .addComponent(campoApellido)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bCrearUsuario)
                                    .addComponent(bEditarUsuario)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labTemporadas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoTemporadas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labEpisodios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(camposEpisodios))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labNombreSeries)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoNombreSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bEliminarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bBuscarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bCrearSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(labelBienvenida)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labUsername)
                    .addComponent(bCrearUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labNombre)
                    .addComponent(bEditarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labApellido)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombrePelicula)
                    .addComponent(campoNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labNombreSeries)
                    .addComponent(campoNombreSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labResumen)
                    .addComponent(campoResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTemporadas)
                    .addComponent(campoTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labYear)
                    .addComponent(campoAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labEpisodios)
                    .addComponent(camposEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDirector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrearPelicula)
                    .addComponent(bCrearSerie))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscarPelicula)
                    .addComponent(bBuscarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminarPelicula)
                    .addComponent(bEliminarSerie))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCrearUsuarioActionPerformed

    private void bCrearPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCrearPeliculaActionPerformed

    private void bBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarPeliculaActionPerformed

    private void bEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarPeliculaActionPerformed

    private void bBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarSerieActionPerformed

    private void bEliminarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarSerieActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarPelicula;
    private javax.swing.JButton bBuscarSerie;
    private javax.swing.JButton bCrearPelicula;
    private javax.swing.JButton bCrearSerie;
    private javax.swing.JButton bCrearUsuario;
    private javax.swing.JButton bEditarUsuario;
    private javax.swing.JButton bEliminarPelicula;
    private javax.swing.JButton bEliminarSerie;
    private javax.swing.JTextField campoAnos;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoDirector;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNombrePelicula;
    private javax.swing.JTextField campoNombreSeries;
    private javax.swing.JTextField campoResumen;
    private javax.swing.JTextField campoTemporadas;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JTextField camposEpisodios;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labApellido;
    private javax.swing.JLabel labDirector;
    private javax.swing.JLabel labEpisodios;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labNombrePelicula;
    private javax.swing.JLabel labNombreSeries;
    private javax.swing.JLabel labResumen;
    private javax.swing.JLabel labTemporadas;
    private javax.swing.JLabel labUsername;
    private javax.swing.JLabel labYear;
    private javax.swing.JLabel labelBienvenida;
    // End of variables declaration//GEN-END:variables

    public Ventana(JButton jButton1, JButton jButton2, JButton jButton3, JButton jButton4, JButton jButton5, JButton jButton6, JLabel jLabel1) {
        this.bCrearUsuario = jButton1;
        this.bEditarUsuario = jButton2;
        this.bCrearPelicula = jButton3;
        this.bBuscarPelicula = jButton4;
        this.bEliminarPelicula = jButton5;
        this.bCrearSerie = jButton6;
        this.labelBienvenida = jLabel1;
    }


}
